#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "molokai"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    
    # autocomplete_method = "coc"
    lint_engine = "ale"
    lint_on_the_fly = true
    lint_on_save = true
    snippet_engine = "ultisnips"
    
    default_indent = 4
    expand_tab = true
    automatic_update = true
    auto_disable_touchpad = false

[[custom_plugins]]
  repo = "fmoralesc/molokayo"
  merged = 0

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "smart"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'checkers'
show_cursor_error = true

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = 'edit'
autosave_timeout = 60000
autosave_events = ['InsertLeave', 'TextChanged']

[[layers]]
name = "colorscheme"

[[custom_plugins]]
repo = "lilydjwg/colorizer"
merged = false

[[layers]]
name = "format"

[[layers]]
name = "lsp"
filetypes = [
    "rust",
    "c",
    "cpp",
    "python"
#    "lua"
  ]
  [layers.override_cmd]
    rust = ["rust-analyzer"]

[[layers]]
  name = "debug"

[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true
  [layer.clang_std]
    cpp = "c20"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = 'lang#clojure'

[[layers]]
  name = "lang#lua"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#html"
  emmet_leader_key = "<C-e>"
  emmet_filetyps = ['html']

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#extra"
