alsa-utils 1.2.6-1
ani-cli-git r538.94efc40-1
arch-install-scripts 24-2
autoconf 2.71-1
autojump 22.5.3-9
automake 1.16.5-1
autotiling-rs-git 0.1.3.r20.g695cfaf-1
base 2-2
betterdiscord-installer-bin 1.1.1-2
bison 3.8.2-4
blackarch-keyring 20180925-5
brave-bin 1:1.38.109-1
brightnessctl 0.5.1-2
cava 0.8.2-1
cbonsai 1.3.1-3
clipman 1.6.1-1
clojure 1.11.1.1105-2
discord 0.0.17-1
downgrade 11.1.0-1
easyeffects 6.2.4-1
edex-ui-bin 2.2.8-1
eslint 8.14.0-1
exa 0.10.1-5
fd 8.3.2-1
figlet-fonts 1.0-3
figlet-fonts-extra 1.0-1
flex 2.6.4-3
funny-manpages 2.3-1
genius 1.0.27-2
gimp 2.10.30-2
gotop-bin 4.1.2-1
grub-customizer 5.1.0-3
intel-ucode 20220419-1
kitty 0.25.0-1
linux-zen 5.17.5.zen1-1
linux-zen-headers 5.17.5.zen1-1
lxappearance-gtk3 0.6.3-4
make 4.3-3
mkinitcpio-firmware 1.3.0-1
nano 6.2-1
ncdu 2.1.1-1
neofetch 7.1.0-2
neovim 0.7.0-3
nerd-fonts-complete 2.1.0-8
network-manager-applet 1.26.0-1
nmap 7.92-1
nwg-wrapper 0.1.2-1
papirus-icon-theme 20220302-1
paru 1.10.0-1
patch 2.7.6-8
pavucontrol 1:5.0+r35+g964f298-1
pipes-rs-git v1.4.7.r0.g2187012-1
pkgconf 1.8.0-1
polkit-gnome 0.105-9
postgresql 14.2-1
pscircle 1.3.1-1
pygtk 2.24.0-12
python-pyalsa 1.2.6-2
python-pylint 2.13.7-1
qbittorrent 4.4.2-2
qmk 1.0.0-2
qt5-quickcontrols2 5.15.3+kde+r4-1
qt5-styleplugins 5.0.0.20170311-27
qt5ct 1.5-2
ranger 1.9.3-4
reflector 2021.11-3
rofi-lbonn-wayland 1.7.3+wayland1-1
rust-analyzer 20220425-1
samsung-unified-driver 1.00.39-5
sddm 0.19.0-8
set 1:8.0.3-3
simple-scan 42.1-1
sl 5.05-2
sof-firmware 2.1.1-1
sway-borders-git r6983.5734188f-1
swayidle 1.7.1-2
swaylock-effects-git r380.a8fc557-1
udiskie 2.4.2-1
ufw 0.36.1-1
unimatrix-git r66.75f7402-1
volantes-cursors 20200506.0-2
vscode-html-languageserver 1.66.1-1
wev 1.0.0-7
wf-recorder 0.2.1-4
wireshark-qt 3.6.3-1
yapf 0.32.0-1
