alsa-utils
ani-cli-git
arch-install-scripts
ascii-image-converter-git
autojump
base
base-devel
betaflight-configurator-bin
betterdiscord-installer-bin
blackarch-keyring
blender
brave-bin
brightnessctl
cava
cbonsai
clojure
cmake
cmake-format
cowsay
cppcheck
discord
downgrade
easyeffects
edex-ui-bin
edgetx-flasher-bin
eslint
exa
expresslrs-configurator
fd
figlet
figlet-fonts
figlet-fonts-extra
flake8
flex
fortune-mod
funny-manpages
gimp
gnu-netcat
grim
grub-customizer
helvum
hexedit
htop
hyprland-bin
hyprpaper-git
imv
inkscape
intel-gpu-tools
intel-ucode
kitty
libva-utils
linux-zen
lolcat
man-db
man-pages
mkinitcpio-firmware
moc-pulse
mpvpaper
nano
ncdu
neofetch
neovim
nerd-fonts-complete
network-manager-applet
nwg-look-bin
nwg-wrapper
papirus-icon-theme
paru
pavucontrol
pipes-rs-git
pkgconf
playerctl
polkit-gnome
postgresql
prettier
prusa-slicer
pscircle
python-psutil
python-pyalsa
python-pylint
python-pywal
python-scipy
qbittorrent
qmk
qt5-quickcontrols2
qt5-styleplugins
qt5ct
ranger
realesrgan-ncnn-vulkan-bin
reflector
ripgrep
rofi-lbonn-wayland
rust-analyzer
samsung-unified-driver
sddm
set
simple-scan
sl
sof-firmware
stylua
teensy-loader
tree
udiskie
ufw
unimatrix-git
volantes-cursors
vscode-html-languageserver
vulkan-extra-layers
vulkan-extra-tools
vulkan-html-docs
vulkan-tools
wasm-pack
webcord-bin
wev
wf-recorder
wine
wine-gecko
wine-mono
wireshark-qt
wl-clipboard-history-git
wlsunset-git
wvkbd
xf86-video-intel
xorg-xeyes
xplr
yapf
zenmap
