alsa-utils
ani-cli-git
arch-install-scripts
autoconf
autojump
automake
autotiling-rs-git
base
betterdiscord-installer-bin
bison
blackarch-keyring
brave-bin
brightnessctl
cava
cbonsai
clojure
cmake
discord
downgrade
easyeffects
edex-ui-bin
eslint
exa
fd
figlet-fonts
figlet-fonts-extra
flex
funny-manpages
genius
gimp
gnu-netcat
gotop-bin
grub-customizer
helvum
htop
imv
intel-gpu-tools
intel-ucode
kitty
lib32-pipewire
libva-utils
linux-zen
linux-zen-headers
lxappearance-gtk3
make
man-db
man-pages
mkinitcpio-firmware
mpvpaper
nano
ncdu
neofetch
neovim
nerd-fonts-complete
network-manager-applet
nwg-wrapper
oguri-git
papirus-icon-theme
paru
patch
pavucontrol
pfetch
pipes-rs-git
playerctl
polkit-gnome
postgresql
pscircle
python-psutil
python-pyalsa
python-pylint
python-pywal
qbittorrent
qmk
qt5-quickcontrols2
qt5-styleplugins
qt5ct
ranger
reflector
rofi-lbonn-wayland
rust-analyzer
samsung-unified-driver
sddm
set
shell-color-scripts
simple-scan
sl
sof-firmware
teensy-loader
udiskie
ufw
unimatrix-git
volantes-cursors
vscode-html-languageserver
wev
wf-recorder
wireshark-qt
wl-clipboard-history-git
wvkbd
yapf
zenmap
